export const GET_PRODUCTS = "GET_PRODUCTS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_END = "ADD_PRODUCT_END";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_END";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_END";
